/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntryType = IDL.Variant({ 'lay' : IDL.Null, 'back' : IDL.Null });
export const Team = IDL.Text;
export const EntryInput = IDL.Record({
  'entryType' : EntryType,
  'rate' : IDL.Float64,
  'favoriteTeam' : Team,
  'matchId' : IDL.Nat,
  'bookieName' : IDL.Text,
  'amount' : IDL.Float64,
});
export const CashflowEntryType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const CashflowInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'entryType' : CashflowEntryType,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const LoanInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'principal' : IDL.Float64,
  'termMonthly' : IDL.Bool,
  'loanTenure' : IDL.Float64,
  'collateral' : IDL.Text,
  'interestRate' : IDL.Float64,
  'borrowerName' : IDL.Text,
});
export const PropertyInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'purchasePrice' : IDL.Float64,
  'acquisitionDate' : IDL.Int,
  'landArea' : IDL.Float64,
  'location' : IDL.Text,
});
export const WealthInputInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'cashLiquid' : IDL.Float64,
  'otherAssets' : IDL.Float64,
  'goldWeight' : IDL.Float64,
  'stocksValue' : IDL.Float64,
  'goldValue' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'team1' : Team,
  'team2' : Team,
  'matchName' : IDL.Text,
});
export const DaywiseSummary = IDL.Record({
  'totalCredit' : IDL.Float64,
  'date' : IDL.Int,
  'netProfitLoss' : IDL.Float64,
  'totalDebit' : IDL.Float64,
});
export const DailyReport = IDL.Record({
  'dailySummaries' : IDL.Vec(DaywiseSummary),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CashflowEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : CashflowEntryType,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'amount' : IDL.Float64,
});
export const CashflowSummary = IDL.Record({
  'totalCredit' : IDL.Float64,
  'netBalance' : IDL.Float64,
  'totalDebit' : IDL.Float64,
});
export const Loan = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Float64,
  'termMonthly' : IDL.Bool,
  'loanTenure' : IDL.Float64,
  'createdAt' : IDL.Int,
  'collateral' : IDL.Text,
  'updatedAt' : IDL.Int,
  'interestRate' : IDL.Float64,
  'borrowerName' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'settled' : IDL.Null,
  'pending' : IDL.Null,
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'team1' : Team,
  'team2' : Team,
  'createdAt' : IDL.Int,
  'winner' : IDL.Opt(Team),
  'updatedAt' : IDL.Int,
  'settledAt' : IDL.Opt(IDL.Int),
  'matchName' : IDL.Text,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Float64,
  'acquisitionDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'landArea' : IDL.Float64,
  'location' : IDL.Text,
});
export const PLSummary = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'totalPL' : IDL.Float64,
  'winner' : IDL.Opt(Team),
  'matchId' : IDL.Nat,
  'team2StrongPL' : IDL.Float64,
  'team1WeakPL' : IDL.Float64,
  'finalScore' : IDL.Opt(IDL.Float64),
  'team1StrongPL' : IDL.Float64,
  'team2WeakPL' : IDL.Float64,
});
export const WealthInput = IDL.Record({
  'id' : IDL.Nat,
  'cashLiquid' : IDL.Float64,
  'createdAt' : IDL.Int,
  'otherAssets' : IDL.Float64,
  'goldWeight' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'stocksValue' : IDL.Float64,
  'goldValue' : IDL.Float64,
});
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : EntryType,
  'createdAt' : IDL.Int,
  'rate' : IDL.Float64,
  'favoriteTeam' : Team,
  'updatedAt' : IDL.Int,
  'matchId' : IDL.Nat,
  'bookieName' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func([EntryInput], [IDL.Nat], []),
  'addOrUpdateCashflowEntry' : IDL.Func([CashflowInput], [IDL.Nat], []),
  'addOrUpdateLoan' : IDL.Func([LoanInput], [IDL.Nat], []),
  'addOrUpdateProperty' : IDL.Func([PropertyInput], [IDL.Nat], []),
  'addOrUpdateWealthInput' : IDL.Func([WealthInputInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([MatchInput], [IDL.Nat], []),
  'deleteCashflowEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteLoan' : IDL.Func([IDL.Nat], [], []),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'deleteWealthInput' : IDL.Func([IDL.Nat], [], []),
  'generateDailyReport' : IDL.Func([], [DailyReport], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCashflowEntry' : IDL.Func([IDL.Nat], [CashflowEntry], ['query']),
  'getCashflowSummary' : IDL.Func([], [CashflowSummary], ['query']),
  'getLoan' : IDL.Func([IDL.Nat], [Loan], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getTeamPLSummary' : IDL.Func([IDL.Nat], [PLSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWealthInput' : IDL.Func([IDL.Nat], [WealthInput], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCashflowEntries' : IDL.Func([], [IDL.Vec(CashflowEntry)], ['query']),
  'listEntries' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
  'listLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'listProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'listWealthInputs' : IDL.Func([], [IDL.Vec(WealthInput)], ['query']),
  'netWorth' : IDL.Func([], [IDL.Float64], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleMatch' : IDL.Func(
      [IDL.Record({ 'winner' : IDL.Text, 'matchId' : IDL.Nat })],
      [],
      [],
    ),
  'totalLendingPortfolio' : IDL.Func([], [IDL.Float64], ['query']),
  'totalPropertyValue' : IDL.Func([], [IDL.Float64], ['query']),
  'totalWealthInputs' : IDL.Func([], [IDL.Float64], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntryType = IDL.Variant({ 'lay' : IDL.Null, 'back' : IDL.Null });
  const Team = IDL.Text;
  const EntryInput = IDL.Record({
    'entryType' : EntryType,
    'rate' : IDL.Float64,
    'favoriteTeam' : Team,
    'matchId' : IDL.Nat,
    'bookieName' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const CashflowEntryType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const CashflowInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'entryType' : CashflowEntryType,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const LoanInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'principal' : IDL.Float64,
    'termMonthly' : IDL.Bool,
    'loanTenure' : IDL.Float64,
    'collateral' : IDL.Text,
    'interestRate' : IDL.Float64,
    'borrowerName' : IDL.Text,
  });
  const PropertyInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'purchasePrice' : IDL.Float64,
    'acquisitionDate' : IDL.Int,
    'landArea' : IDL.Float64,
    'location' : IDL.Text,
  });
  const WealthInputInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'cashLiquid' : IDL.Float64,
    'otherAssets' : IDL.Float64,
    'goldWeight' : IDL.Float64,
    'stocksValue' : IDL.Float64,
    'goldValue' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'team1' : Team,
    'team2' : Team,
    'matchName' : IDL.Text,
  });
  const DaywiseSummary = IDL.Record({
    'totalCredit' : IDL.Float64,
    'date' : IDL.Int,
    'netProfitLoss' : IDL.Float64,
    'totalDebit' : IDL.Float64,
  });
  const DailyReport = IDL.Record({
    'dailySummaries' : IDL.Vec(DaywiseSummary),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CashflowEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : CashflowEntryType,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const CashflowSummary = IDL.Record({
    'totalCredit' : IDL.Float64,
    'netBalance' : IDL.Float64,
    'totalDebit' : IDL.Float64,
  });
  const Loan = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Float64,
    'termMonthly' : IDL.Bool,
    'loanTenure' : IDL.Float64,
    'createdAt' : IDL.Int,
    'collateral' : IDL.Text,
    'updatedAt' : IDL.Int,
    'interestRate' : IDL.Float64,
    'borrowerName' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'settled' : IDL.Null,
    'pending' : IDL.Null,
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'team1' : Team,
    'team2' : Team,
    'createdAt' : IDL.Int,
    'winner' : IDL.Opt(Team),
    'updatedAt' : IDL.Int,
    'settledAt' : IDL.Opt(IDL.Int),
    'matchName' : IDL.Text,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Float64,
    'acquisitionDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'landArea' : IDL.Float64,
    'location' : IDL.Text,
  });
  const PLSummary = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'totalPL' : IDL.Float64,
    'winner' : IDL.Opt(Team),
    'matchId' : IDL.Nat,
    'team2StrongPL' : IDL.Float64,
    'team1WeakPL' : IDL.Float64,
    'finalScore' : IDL.Opt(IDL.Float64),
    'team1StrongPL' : IDL.Float64,
    'team2WeakPL' : IDL.Float64,
  });
  const WealthInput = IDL.Record({
    'id' : IDL.Nat,
    'cashLiquid' : IDL.Float64,
    'createdAt' : IDL.Int,
    'otherAssets' : IDL.Float64,
    'goldWeight' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'stocksValue' : IDL.Float64,
    'goldValue' : IDL.Float64,
  });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : EntryType,
    'createdAt' : IDL.Int,
    'rate' : IDL.Float64,
    'favoriteTeam' : Team,
    'updatedAt' : IDL.Int,
    'matchId' : IDL.Nat,
    'bookieName' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func([EntryInput], [IDL.Nat], []),
    'addOrUpdateCashflowEntry' : IDL.Func([CashflowInput], [IDL.Nat], []),
    'addOrUpdateLoan' : IDL.Func([LoanInput], [IDL.Nat], []),
    'addOrUpdateProperty' : IDL.Func([PropertyInput], [IDL.Nat], []),
    'addOrUpdateWealthInput' : IDL.Func([WealthInputInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([MatchInput], [IDL.Nat], []),
    'deleteCashflowEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteLoan' : IDL.Func([IDL.Nat], [], []),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'deleteWealthInput' : IDL.Func([IDL.Nat], [], []),
    'generateDailyReport' : IDL.Func([], [DailyReport], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCashflowEntry' : IDL.Func([IDL.Nat], [CashflowEntry], ['query']),
    'getCashflowSummary' : IDL.Func([], [CashflowSummary], ['query']),
    'getLoan' : IDL.Func([IDL.Nat], [Loan], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getTeamPLSummary' : IDL.Func([IDL.Nat], [PLSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWealthInput' : IDL.Func([IDL.Nat], [WealthInput], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCashflowEntries' : IDL.Func([], [IDL.Vec(CashflowEntry)], ['query']),
    'listEntries' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
    'listLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'listProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'listWealthInputs' : IDL.Func([], [IDL.Vec(WealthInput)], ['query']),
    'netWorth' : IDL.Func([], [IDL.Float64], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleMatch' : IDL.Func(
        [IDL.Record({ 'winner' : IDL.Text, 'matchId' : IDL.Nat })],
        [],
        [],
      ),
    'totalLendingPortfolio' : IDL.Func([], [IDL.Float64], ['query']),
    'totalPropertyValue' : IDL.Func([], [IDL.Float64], ['query']),
    'totalWealthInputs' : IDL.Func([], [IDL.Float64], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };