/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CashflowEntry {
  'id' : bigint,
  'entryType' : CashflowEntryType,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'amount' : number,
}
export type CashflowEntryType = { 'credit' : null } |
  { 'debit' : null };
export interface CashflowInput {
  'id' : [] | [bigint],
  'entryType' : CashflowEntryType,
  'description' : string,
  'amount' : number,
}
export interface CashflowSummary {
  'totalCredit' : number,
  'netBalance' : number,
  'totalDebit' : number,
}
export interface DailyReport { 'dailySummaries' : Array<DaywiseSummary> }
export interface DaywiseSummary {
  'totalCredit' : number,
  'date' : bigint,
  'netProfitLoss' : number,
  'totalDebit' : number,
}
export interface Entry {
  'id' : bigint,
  'entryType' : EntryType,
  'createdAt' : bigint,
  'rate' : number,
  'favoriteTeam' : Team,
  'updatedAt' : bigint,
  'matchId' : bigint,
  'bookieName' : string,
  'amount' : number,
}
export interface EntryInput {
  'entryType' : EntryType,
  'rate' : number,
  'favoriteTeam' : Team,
  'matchId' : bigint,
  'bookieName' : string,
  'amount' : number,
}
export type EntryType = { 'lay' : null } |
  { 'back' : null };
export interface Loan {
  'id' : bigint,
  'principal' : number,
  'termMonthly' : boolean,
  'loanTenure' : number,
  'createdAt' : bigint,
  'collateral' : string,
  'updatedAt' : bigint,
  'interestRate' : number,
  'borrowerName' : string,
}
export interface LoanInput {
  'id' : [] | [bigint],
  'principal' : number,
  'termMonthly' : boolean,
  'loanTenure' : number,
  'collateral' : string,
  'interestRate' : number,
  'borrowerName' : string,
}
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'team1' : Team,
  'team2' : Team,
  'createdAt' : bigint,
  'winner' : [] | [Team],
  'updatedAt' : bigint,
  'settledAt' : [] | [bigint],
  'matchName' : string,
}
export interface MatchInput {
  'id' : [] | [bigint],
  'team1' : Team,
  'team2' : Team,
  'matchName' : string,
}
export type MatchStatus = { 'settled' : null } |
  { 'pending' : null } |
  { 'in_progress' : null } |
  { 'completed' : null };
export interface PLSummary {
  'id' : bigint,
  'status' : MatchStatus,
  'team1' : string,
  'team2' : string,
  'totalPL' : number,
  'winner' : [] | [Team],
  'matchId' : bigint,
  'team2StrongPL' : number,
  'team1WeakPL' : number,
  'finalScore' : [] | [number],
  'team1StrongPL' : number,
  'team2WeakPL' : number,
}
export interface Property {
  'id' : bigint,
  'purchasePrice' : number,
  'acquisitionDate' : bigint,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'landArea' : number,
  'location' : string,
}
export interface PropertyInput {
  'id' : [] | [bigint],
  'purchasePrice' : number,
  'acquisitionDate' : bigint,
  'landArea' : number,
  'location' : string,
}
export type Team = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WealthInput {
  'id' : bigint,
  'cashLiquid' : number,
  'createdAt' : bigint,
  'otherAssets' : number,
  'goldWeight' : number,
  'updatedAt' : bigint,
  'stocksValue' : number,
  'goldValue' : number,
}
export interface WealthInputInput {
  'id' : [] | [bigint],
  'cashLiquid' : number,
  'otherAssets' : number,
  'goldWeight' : number,
  'stocksValue' : number,
  'goldValue' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntry' : ActorMethod<[EntryInput], bigint>,
  'addOrUpdateCashflowEntry' : ActorMethod<[CashflowInput], bigint>,
  'addOrUpdateLoan' : ActorMethod<[LoanInput], bigint>,
  'addOrUpdateProperty' : ActorMethod<[PropertyInput], bigint>,
  'addOrUpdateWealthInput' : ActorMethod<[WealthInputInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[MatchInput], bigint>,
  'deleteCashflowEntry' : ActorMethod<[bigint], undefined>,
  'deleteLoan' : ActorMethod<[bigint], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'deleteWealthInput' : ActorMethod<[bigint], undefined>,
  'generateDailyReport' : ActorMethod<[], DailyReport>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashflowEntry' : ActorMethod<[bigint], CashflowEntry>,
  'getCashflowSummary' : ActorMethod<[], CashflowSummary>,
  'getLoan' : ActorMethod<[bigint], Loan>,
  'getMatch' : ActorMethod<[bigint], Match>,
  'getProperty' : ActorMethod<[bigint], Property>,
  'getTeamPLSummary' : ActorMethod<[bigint], PLSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWealthInput' : ActorMethod<[bigint], WealthInput>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCashflowEntries' : ActorMethod<[], Array<CashflowEntry>>,
  'listEntries' : ActorMethod<[bigint], Array<Entry>>,
  'listLoans' : ActorMethod<[], Array<Loan>>,
  'listMatches' : ActorMethod<[], Array<Match>>,
  'listProperties' : ActorMethod<[], Array<Property>>,
  'listWealthInputs' : ActorMethod<[], Array<WealthInput>>,
  'netWorth' : ActorMethod<[], number>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleMatch' : ActorMethod<
    [{ 'winner' : string, 'matchId' : bigint }],
    undefined
  >,
  'totalLendingPortfolio' : ActorMethod<[], number>,
  'totalPropertyValue' : ActorMethod<[], number>,
  'totalWealthInputs' : ActorMethod<[], number>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];