/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WealthInputInput {
    id?: bigint;
    cashLiquid: number;
    otherAssets: number;
    goldWeight: number;
    stocksValue: number;
    goldValue: number;
}
export interface CashflowInput {
    id?: bigint;
    entryType: CashflowEntryType;
    description: string;
    amount: number;
}
export interface DaywiseSummary {
    totalCredit: number;
    date: bigint;
    netProfitLoss: number;
    totalDebit: number;
}
export interface CashflowEntry {
    id: bigint;
    entryType: CashflowEntryType;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    amount: number;
}
export interface MatchInput {
    id?: bigint;
    team1: Team;
    team2: Team;
    matchName: string;
}
export interface EntryInput {
    entryType: EntryType;
    rate: number;
    favoriteTeam: Team;
    matchId: bigint;
    bookieName: string;
    amount: number;
}
export interface Loan {
    id: bigint;
    principal: number;
    termMonthly: boolean;
    loanTenure: number;
    createdAt: bigint;
    collateral: string;
    updatedAt: bigint;
    interestRate: number;
    borrowerName: string;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    team1: Team;
    team2: Team;
    createdAt: bigint;
    winner?: Team;
    updatedAt: bigint;
    settledAt?: bigint;
    matchName: string;
}
export interface PLSummary {
    id: bigint;
    status: MatchStatus;
    team1: string;
    team2: string;
    totalPL: number;
    winner?: Team;
    matchId: bigint;
    team2StrongPL: number;
    team1WeakPL: number;
    finalScore?: number;
    team1StrongPL: number;
    team2WeakPL: number;
}
export interface WealthInput {
    id: bigint;
    cashLiquid: number;
    createdAt: bigint;
    otherAssets: number;
    goldWeight: number;
    updatedAt: bigint;
    stocksValue: number;
    goldValue: number;
}
export interface PropertyInput {
    id?: bigint;
    purchasePrice: number;
    acquisitionDate: bigint;
    landArea: number;
    location: string;
}
export interface Property {
    id: bigint;
    purchasePrice: number;
    acquisitionDate: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    landArea: number;
    location: string;
}
export interface Entry {
    id: bigint;
    entryType: EntryType;
    createdAt: bigint;
    rate: number;
    favoriteTeam: Team;
    updatedAt: bigint;
    matchId: bigint;
    bookieName: string;
    amount: number;
}
export interface CashflowSummary {
    totalCredit: number;
    netBalance: number;
    totalDebit: number;
}
export interface LoanInput {
    id?: bigint;
    principal: number;
    termMonthly: boolean;
    loanTenure: number;
    collateral: string;
    interestRate: number;
    borrowerName: string;
}
export interface DailyReport {
    dailySummaries: Array<DaywiseSummary>;
}
export interface UserProfile {
    name: string;
}
export type Team = string;
export enum CashflowEntryType {
    credit = "credit",
    debit = "debit"
}
export enum EntryType {
    lay = "lay",
    back = "back"
}
export enum MatchStatus {
    settled = "settled",
    pending = "pending",
    in_progress = "in_progress",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEntry(input: EntryInput): Promise<bigint>;
    addOrUpdateCashflowEntry(input: CashflowInput): Promise<bigint>;
    addOrUpdateLoan(loanInput: LoanInput): Promise<bigint>;
    addOrUpdateProperty(propertyInput: PropertyInput): Promise<bigint>;
    addOrUpdateWealthInput(wealthInput: WealthInputInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMatch(input: MatchInput): Promise<bigint>;
    deleteCashflowEntry(id: bigint): Promise<void>;
    deleteLoan(id: bigint): Promise<void>;
    deleteProperty(id: bigint): Promise<void>;
    deleteWealthInput(id: bigint): Promise<void>;
    generateDailyReport(): Promise<DailyReport>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCashflowEntry(id: bigint): Promise<CashflowEntry>;
    getCashflowSummary(): Promise<CashflowSummary>;
    getLoan(id: bigint): Promise<Loan>;
    getMatch(matchId: bigint): Promise<Match>;
    getProperty(id: bigint): Promise<Property>;
    getTeamPLSummary(matchId: bigint): Promise<PLSummary>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWealthInput(id: bigint): Promise<WealthInput>;
    isCallerAdmin(): Promise<boolean>;
    listCashflowEntries(): Promise<Array<CashflowEntry>>;
    listEntries(matchId: bigint): Promise<Array<Entry>>;
    listLoans(): Promise<Array<Loan>>;
    listMatches(): Promise<Array<Match>>;
    listProperties(): Promise<Array<Property>>;
    listWealthInputs(): Promise<Array<WealthInput>>;
    netWorth(): Promise<number>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    settleMatch(arg0: {
        winner: string;
        matchId: bigint;
    }): Promise<void>;
    totalLendingPortfolio(): Promise<number>;
    totalPropertyValue(): Promise<number>;
    totalWealthInputs(): Promise<number>;
}
import type { CashflowEntry as _CashflowEntry, CashflowEntryType as _CashflowEntryType, CashflowInput as _CashflowInput, Entry as _Entry, EntryInput as _EntryInput, EntryType as _EntryType, LoanInput as _LoanInput, Match as _Match, MatchInput as _MatchInput, MatchStatus as _MatchStatus, PLSummary as _PLSummary, PropertyInput as _PropertyInput, Team as _Team, UserProfile as _UserProfile, UserRole as _UserRole, WealthInputInput as _WealthInputInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEntry(arg0: EntryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEntry(to_candid_EntryInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEntry(to_candid_EntryInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateCashflowEntry(arg0: CashflowInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCashflowEntry(to_candid_CashflowInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCashflowEntry(to_candid_CashflowInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateLoan(arg0: LoanInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateLoan(to_candid_LoanInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateLoan(to_candid_LoanInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateProperty(arg0: PropertyInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProperty(to_candid_PropertyInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProperty(to_candid_PropertyInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateWealthInput(arg0: WealthInputInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateWealthInput(to_candid_WealthInputInput_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateWealthInput(to_candid_WealthInputInput_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMatch(arg0: MatchInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(to_candid_MatchInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(to_candid_MatchInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCashflowEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCashflowEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCashflowEntry(arg0);
            return result;
        }
    }
    async deleteLoan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLoan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLoan(arg0);
            return result;
        }
    }
    async deleteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async deleteWealthInput(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWealthInput(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWealthInput(arg0);
            return result;
        }
    }
    async generateDailyReport(): Promise<DailyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDailyReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDailyReport();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashflowEntry(arg0: bigint): Promise<CashflowEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashflowEntry(arg0);
                return from_candid_CashflowEntry_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashflowEntry(arg0);
            return from_candid_CashflowEntry_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashflowSummary(): Promise<CashflowSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashflowSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashflowSummary();
            return result;
        }
    }
    async getLoan(arg0: bigint): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoan(arg0);
            return result;
        }
    }
    async getMatch(arg0: bigint): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_Match_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_Match_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return result;
        }
    }
    async getTeamPLSummary(arg0: bigint): Promise<PLSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamPLSummary(arg0);
                return from_candid_PLSummary_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamPLSummary(arg0);
            return from_candid_PLSummary_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWealthInput(arg0: bigint): Promise<WealthInput> {
        if (this.processError) {
            try {
                const result = await this.actor.getWealthInput(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWealthInput(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCashflowEntries(): Promise<Array<CashflowEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCashflowEntries();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCashflowEntries();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEntries(arg0: bigint): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEntries(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEntries(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLoans(): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLoans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLoans();
            return result;
        }
    }
    async listMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProperties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProperties();
            return result;
        }
    }
    async listWealthInputs(): Promise<Array<WealthInput>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWealthInputs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWealthInputs();
            return result;
        }
    }
    async netWorth(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.netWorth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.netWorth();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async settleMatch(arg0: {
        winner: string;
        matchId: bigint;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.settleMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleMatch(arg0);
            return result;
        }
    }
    async totalLendingPortfolio(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.totalLendingPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.totalLendingPortfolio();
            return result;
        }
    }
    async totalPropertyValue(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.totalPropertyValue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.totalPropertyValue();
            return result;
        }
    }
    async totalWealthInputs(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.totalWealthInputs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.totalWealthInputs();
            return result;
        }
    }
}
function from_candid_CashflowEntryType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CashflowEntryType): CashflowEntryType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CashflowEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CashflowEntry): CashflowEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EntryType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntryType): EntryType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Entry_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Entry): Entry {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PLSummary_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PLSummary): PLSummary {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    entryType: _CashflowEntryType;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    amount: number;
}): {
    id: bigint;
    entryType: CashflowEntryType;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    amount: number;
} {
    return {
        id: value.id,
        entryType: from_candid_CashflowEntryType_n24(_uploadFile, _downloadFile, value.entryType),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        amount: value.amount
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    team1: _Team;
    team2: _Team;
    createdAt: bigint;
    winner: [] | [_Team];
    updatedAt: bigint;
    settledAt: [] | [bigint];
    matchName: string;
}): {
    id: bigint;
    status: MatchStatus;
    team1: Team;
    team2: Team;
    createdAt: bigint;
    winner?: Team;
    updatedAt: bigint;
    settledAt?: bigint;
    matchName: string;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n28(_uploadFile, _downloadFile, value.status),
        team1: value.team1,
        team2: value.team2,
        createdAt: value.createdAt,
        winner: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.winner)),
        updatedAt: value.updatedAt,
        settledAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.settledAt)),
        matchName: value.matchName
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    team1: string;
    team2: string;
    totalPL: number;
    winner: [] | [_Team];
    matchId: bigint;
    team2StrongPL: number;
    team1WeakPL: number;
    finalScore: [] | [number];
    team1StrongPL: number;
    team2WeakPL: number;
}): {
    id: bigint;
    status: MatchStatus;
    team1: string;
    team2: string;
    totalPL: number;
    winner?: Team;
    matchId: bigint;
    team2StrongPL: number;
    team1WeakPL: number;
    finalScore?: number;
    team1StrongPL: number;
    team2WeakPL: number;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n28(_uploadFile, _downloadFile, value.status),
        team1: value.team1,
        team2: value.team2,
        totalPL: value.totalPL,
        winner: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.winner)),
        matchId: value.matchId,
        team2StrongPL: value.team2StrongPL,
        team1WeakPL: value.team1WeakPL,
        finalScore: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.finalScore)),
        team1StrongPL: value.team1StrongPL,
        team2WeakPL: value.team2WeakPL
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    entryType: _EntryType;
    createdAt: bigint;
    rate: number;
    favoriteTeam: _Team;
    updatedAt: bigint;
    matchId: bigint;
    bookieName: string;
    amount: number;
}): {
    id: bigint;
    entryType: EntryType;
    createdAt: bigint;
    rate: number;
    favoriteTeam: Team;
    updatedAt: bigint;
    matchId: bigint;
    bookieName: string;
    amount: number;
} {
    return {
        id: value.id,
        entryType: from_candid_EntryType_n39(_uploadFile, _downloadFile, value.entryType),
        createdAt: value.createdAt,
        rate: value.rate,
        favoriteTeam: value.favoriteTeam,
        updatedAt: value.updatedAt,
        matchId: value.matchId,
        bookieName: value.bookieName,
        amount: value.amount
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): CashflowEntryType {
    return "credit" in value ? CashflowEntryType.credit : "debit" in value ? CashflowEntryType.debit : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    settled: null;
} | {
    pending: null;
} | {
    in_progress: null;
} | {
    completed: null;
}): MatchStatus {
    return "settled" in value ? MatchStatus.settled : "pending" in value ? MatchStatus.pending : "in_progress" in value ? MatchStatus.in_progress : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lay: null;
} | {
    back: null;
}): EntryType {
    return "lay" in value ? EntryType.lay : "back" in value ? EntryType.back : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CashflowEntry>): Array<CashflowEntry> {
    return value.map((x)=>from_candid_CashflowEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Entry>): Array<Entry> {
    return value.map((x)=>from_candid_Entry_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n26(_uploadFile, _downloadFile, x));
}
function to_candid_CashflowEntryType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CashflowEntryType): _CashflowEntryType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CashflowInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CashflowInput): _CashflowInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_EntryInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntryInput): _EntryInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EntryType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntryType): _EntryType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LoanInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanInput): _LoanInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_MatchInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchInput): _MatchInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyInput): _PropertyInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_WealthInputInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WealthInputInput): _WealthInputInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    principal: number;
    termMonthly: boolean;
    loanTenure: number;
    collateral: string;
    interestRate: number;
    borrowerName: string;
}): {
    id: [] | [bigint];
    principal: number;
    termMonthly: boolean;
    loanTenure: number;
    collateral: string;
    interestRate: number;
    borrowerName: string;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        principal: value.principal,
        termMonthly: value.termMonthly,
        loanTenure: value.loanTenure,
        collateral: value.collateral,
        interestRate: value.interestRate,
        borrowerName: value.borrowerName
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    purchasePrice: number;
    acquisitionDate: bigint;
    landArea: number;
    location: string;
}): {
    id: [] | [bigint];
    purchasePrice: number;
    acquisitionDate: bigint;
    landArea: number;
    location: string;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        purchasePrice: value.purchasePrice,
        acquisitionDate: value.acquisitionDate,
        landArea: value.landArea,
        location: value.location
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    cashLiquid: number;
    otherAssets: number;
    goldWeight: number;
    stocksValue: number;
    goldValue: number;
}): {
    id: [] | [bigint];
    cashLiquid: number;
    otherAssets: number;
    goldWeight: number;
    stocksValue: number;
    goldValue: number;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        cashLiquid: value.cashLiquid,
        otherAssets: value.otherAssets,
        goldWeight: value.goldWeight,
        stocksValue: value.stocksValue,
        goldValue: value.goldValue
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    team1: Team;
    team2: Team;
    matchName: string;
}): {
    id: [] | [bigint];
    team1: _Team;
    team2: _Team;
    matchName: string;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        team1: value.team1,
        team2: value.team2,
        matchName: value.matchName
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entryType: EntryType;
    rate: number;
    favoriteTeam: Team;
    matchId: bigint;
    bookieName: string;
    amount: number;
}): {
    entryType: _EntryType;
    rate: number;
    favoriteTeam: _Team;
    matchId: bigint;
    bookieName: string;
    amount: number;
} {
    return {
        entryType: to_candid_EntryType_n3(_uploadFile, _downloadFile, value.entryType),
        rate: value.rate,
        favoriteTeam: value.favoriteTeam,
        matchId: value.matchId,
        bookieName: value.bookieName,
        amount: value.amount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    entryType: CashflowEntryType;
    description: string;
    amount: number;
}): {
    id: [] | [bigint];
    entryType: _CashflowEntryType;
    description: string;
    amount: number;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        entryType: to_candid_CashflowEntryType_n7(_uploadFile, _downloadFile, value.entryType),
        description: value.description,
        amount: value.amount
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntryType): {
    lay: null;
} | {
    back: null;
} {
    return value == EntryType.lay ? {
        lay: null
    } : value == EntryType.back ? {
        back: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CashflowEntryType): {
    credit: null;
} | {
    debit: null;
} {
    return value == CashflowEntryType.credit ? {
        credit: null
    } : value == CashflowEntryType.debit ? {
        debit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
